role: Community engagement
tasks: 
  - Responding to questions on Discord and mailing lists
  - Managing and triaging conversations on Discord and mailing lists
current_leads:
  - Jenna Swarthout Goddard
current_members:
  - All core devs
historical_leads:
  - Oliver Beckstein
  - Irfan Alibay
historical_members: []
