role: Community engagement
tasks: 
  - Responding to questions on [Discord](https://discord.com/channels/807348386012987462/) and [GitHub Discussions](https://github.com/MDAnalysis/mdanalysis/discussions)
  - Managing and triaging conversations on [Discord](https://discord.com/channels/807348386012987462/) and [GitHub Discussions](https://github.com/MDAnalysis/mdanalysis/discussions)
  - General management and administration of social accounts (i.e., [LinkedIn](https://linkedin.com/company/mdanalysis), [Bluesky](https://bsky.app/profile/mdanalysis.bsky.social)), [website](https://www.mdanalysis.org), and [blog](https://www.mdanalysis.org/blog/), including...
    
    - *Posting announcements of new developments*
    - *Moderating content*

current_members:
  - "[Brady Johnston](https://github.com/bradyajohnston)"
  - "[Egor Marin](https://github.com/marinegor)"
  - "[Jenna Swarthout Goddard](https://github.com/jennaswa)"
  - "[Oliver Beckstein](https://github.com/orbeckst)"
  - "[Rocco Meli](https://github.com/RMeli)"
  - "[Yuxuan Zhuang](https://github.com/yuxuanzhuang)"
