role: Non-core library maintenance
description: |
  The non-core library maintenance team is responsible for
  managing other packages that are directly
  maintained by the MDAnalysis organization.

tasks:
  - Managing issues and pull-requests for sub-projects
  - Managing new features and updates
  - Managing maintenance
  - Working with CI and CD team and infrastructure
subroles:

  - subrole: distopia
    current_members:
      - "[Richard Gowers](https://github.com/richardjgowers)"
      - "[Hugo MacDermott-Opeskin](https://github.com/hmacdope)"
      - "[Rocco Meli](https://github.com/RMeli)"

  - subrole: cookiecutter-mdakit
    current_members:
      - "[Lily Wang](https://github.com/lilyminium)"
      - "[Irfan Alibay](https://github.com/IAlibay)"

  - subrole: mda-encore
    current_members: []
    
  - subrole: hole2-mdakit
    current_members:
      - "[Lily Wang](https://github.com/lilyminium)"

  - subrole: benchmarks
    current_members:
      - "[Oliver Beckstein](https://github.com/orbeckst)"

  - subrole: GridDataFormats
    current_members:
      - "[Irfan Alibay](https://github.com/IAlibay)"
      - "[Oliver Beckstein](https://github.com/orbeckst)"
  
  - subrole: MDAnalysisData
    current_members:
      - "[Irfan Alibay](https://github.com/IAlibay)"
      - "[Oliver Beckstein](https://github.com/orbeckst)"
  
  - subrole: mda-xrlib and other utilities
    current_members:
      - [Irfan Alibay](https://github.com/IAlibay) 
  
  - subrole: pyedr
    current_members:
      - [Irfan Alibay](https://github.com/IAlibay)

  - subrole: pytng
    current_members:
      - [Hugo MacDermott-Opeskin](https://github.com/hmacdope)

  - subrole: PathSimAnalysis
    current_members:
      - [Oliver Beckstein](https://github.com/orbeckst)

  - subrole: waterdynamics
    current_members:
      - [Fiona Naughton](https://github.com/fiona-naughton)
